name: Fetch and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Fetch Data
        run: |
          ./scripts/fetch-shootings.py
          ./scripts/fetch-barrels.py
      - name: Build
        run: |
          npm install
      - name: Deploy
        run: |
          ./scripts/deploy.sh