name: Fetch and Deploy

on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Fetch Shootings
        run: ./scripts/fetch-shootings.py

      - name: Fetch Barrels
        run: ./scripts/fetch-barrels.py

      - name: Build
        run: |
          npm install
          npm run build
        env:
          VITE_MAPBOX_API_TOKEN: ${{ secrets.VITE_MAPBOX_API_TOKEN }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_SENTRY_API_TOKEN: ${{ secrets.VITE_SENTRY_API_TOKEN }}

      - name: Deploy 🚀
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: pdx-shootings
          bucket-region: us-west-2
          dist-id: E1BCPAYFFGWOA6
          invalidation: /
          delete-removed: true
          private: true